### ISSUE TITLE
[Bug] 图文混排消息序列到 satori 适配器失败

### ISSUE THREAD

**Issue by StarHeartHunt** [nonebot/plugin-alconna#13]
## 请确认：
* [ x ] 问题的标题明确
* [ x ] 我翻阅过其他的issue并且找不到类似的问题
* [ x ] 我已经阅读了[相关文档](https://nonebot.dev/docs/next/best-practice/alconna/) 并仍然认为这是一个Bug

# Bug

## 问题

图文混排消息序列到 satori 适配器失败

## 如何复现

使用 UniMessage 构建图文混排消息发送到 satori 平台，例如：
```
await test.send(
        UniMessage(
            [
                Text(
                    f"{domain.group_alias}统计：\n当前CDN回源带宽数据为：{value:.2f}Mbps"
                ),
                Image(raw={"data": await generate_src_image(stats)}), # BytesIO
            ]
        )
    )
```

## 预期行为

无错误发生

## 使用环境:
- Python 版本: 
- NoneBot2 版本:
- Alconna 版本: 

## 日志/截图

```python
10-21 17:17:56 [DEBUG] nonebot | Checking for matchers in priority 1...
10-21 17:17:56 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.aliyun.plugins.aliyun_cdn, lineno=23)
10-21 17:17:56 [DEBUG] nonebot | Running Matcher(type='message', module=src.plugins.aliyun.plugins.aliyun_cdn, lineno=23)
10-21 17:17:56 [DEBUG] nonebot | Running handler Dependent(call=handle_http_code)
10-21 17:17:58 [INFO] nonebot | AlconnaMatcher(type='', module=src.plugins.aliyun.plugins.aliyun_cdn) running complete
10-21 17:17:58 [ERROR] nonebot | Running AlconnaMatcher(type='', module=src.plugins.aliyun.plugins.aliyun_cdn) failed.
Traceback (most recent call last):
  File "D:\PythonWorkspace\BotFooChanReborn\bot.py", line 21, in <module>
    nonebot.run(app="__mp_main__:app")
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\site-packages\nonebot\drivers\fastapi.py", line 201, in run
    uvicorn.run(
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 821, in simple_run
    await handler(
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\PythonWorkspace\BotFooChanReborn\src\plugins\aliyun\plugins\aliyun_cdn\__init__.py", line 143, in handle_src_bandwidth
    await asyncio.gather(
  File "D:\PythonWorkspace\BotFooChanReborn\src\plugins\aliyun\plugins\aliyun_cdn\__init__.py", line 89, in resolve_src_bandwidth
    await src_bandwidth.send(
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\site-packages\nonebot_plugin_alconna\matcher.py", line 362, in send
    res = await _message.export(bot, fallback)
  File "D:\DevEnv\miniconda3\envs\botfoochan\Lib\site-packages\nonebot_plugin_alconna\uniseg\message.py", line 484, in export
    raise SerializeFailed(lang.require("nbp-uniseg", "failed").format(target=self, adapter=adapter_name))
nonebot_plugin_alconna.uniseg.export.SerializeFailed: 无法将 [Text(text='Mooncell统计：\n当前CDN回源带宽数据为：37.45Mbps', style=None), Image(id=None, url=None, path=None, raw={'data': <_io.BytesIO object at 0x0000017815D90E50>}, name='image.png')] 序列化为适配器 Satori 下的消息
```

**Comment by RF-Tar-Railt** [comment]
你在satori下得带上mimetype

**Comment by RF-Tar-Railt** [comment]
{"data": XXX, "mimetype": "image/png"} 这样的
