### ISSUE TITLE
Bug: Extension 依赖注入优先级低于其他插件默认依赖注入

### ISSUE THREAD

**Issue by MelodyKnit** [nonebot/plugin-alconna#21]
## 问题

在使用了 extension 时，仍然使用了其他插件提供的依赖注入，如 plugin-orm 的 `Model`。

## 依赖版本

nonebot-plugin-orm: 0.4.1
nonebot-plugin-alconna: 0.31.0 

## 代码复现

```python
from arclet.alconna import Alconna
from nonebot.adapters import Bot, Event
from nonebot_plugin_alconna import Interface, on_alconna, Alconna
from nonebot_plugin_alconna.extension import DefaultExtension
from nonebot_plugin_orm import get_session
from sqlalchemy.orm import selectinload
from sqlalchemy import select

from utils.models import Bind, User


class UserExtension(DefaultExtension):
    def __init__(self) -> None:
        self.params = {}

    async def permission_check(self, bot: Bot, event: Event, command: Alconna) -> bool:
        async with get_session() as session:
            account_id = event.get_user_id()
            platform_id = 1
            bind = await session.scalars(
                select(Bind)
                .where(Bind.platform_id == platform_id)
                .where(Bind.account_id == account_id)
                .options(selectinload(Bind.user))
            )
            if bind := bind.one_or_none():
                self.params["user"] = bind.user
                return True
        return False

    def catch(self, interface: Interface):
        return self.params.get(interface.name)


test = on_alconna(Alconna("test"), block=True, extensions=[UserExtension])


@test.handle()
async def _(user: User):
    print(user)

```

## 错误信息

```sh
10-31 17:50:12 [ERROR] nonebot | Running AlconnaMatcher(type='', module=src.managers.teacher, lineno=15) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "D:\Software\anaconda3\envs\classbot\lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "D:\Software\anaconda3\envs\classbot\lib\site-packages\nonebot\drivers\none.py", line 70, in run
    loop.run_until_complete(self._serve())
  File "D:\Software\anaconda3\envs\classbot\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\Software\anaconda3\envs\classbot\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Software\anaconda3\envs\classbot\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Software\anaconda3\envs\classbot\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\Software\anaconda3\envs\classbot\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Software\anaconda3\envs\classbot\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\Software\anaconda3\envs\classbot\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Software\anaconda3\envs\classbot\lib\site-packages\nonebot\internal\matcher\matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Software\anaconda3\envs\classbot\lib\site-packages\nonebot\internal\matcher\matcher.py", line 821, in simple_run
    await handler(
  File "D:\Software\anaconda3\envs\classbot\lib\site-packages\nonebot\dependencies\__init__.py", line 109, in __call__
    values = await self.solve(**kwargs)
  File "D:\Software\anaconda3\envs\classbot\lib\site-packages\nonebot\dependencies\__init__.py", line 221, in solve
    values = await asyncio.gather(
  File "D:\Software\anaconda3\envs\classbot\lib\site-packages\nonebot\dependencies\__init__.py", line 209, in _solve_field
    value = await param._solve(**params)
  File "D:\Software\anaconda3\envs\classbot\lib\site-packages\nonebot\internal\params.py", line 225, in _solve
    return await task
  File "D:\Software\anaconda3\envs\classbot\lib\site-packages\nonebot_plugin_orm\utils.py", line 136, in dependency
    result = await result
  File "D:\Software\anaconda3\envs\classbot\lib\site-packages\sqlalchemy\ext\asyncio\result.py", line 614, in one_or_none
    return await greenlet_spawn(self._only_one_row, True, False, False)
  File "D:\Software\anaconda3\envs\classbot\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 192, in greenlet_spawn
    result = context.switch(value)
  File "D:\Software\anaconda3\envs\classbot\lib\site-packages\sqlalchemy\engine\result.py", line 813, in _only_one_row
    raise exc.MultipleResultsFound(
sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when one or none was required
```

需要将`User`写成`User | Any`才不会触发这个异常

```python
@test.handle()
async def _(user: User | Any):
    print(user)
```

**Comment by RF-Tar-Railt** [comment]
0.31.1 后要求 `UserExtension` 同时实现 `before_catch` 与 `catch` 才能实现自定义依赖注入
