### ISSUE TITLE
[Bug]无法正常加载该插件

### ISSUE THREAD

**Issue by cute-cirno** [nonebot/plugin-alconna#52]
## 请确认：

* [ x] 问题的标题明确
* [ x] 我翻阅过其他的issue并且找不到类似的问题
* [ x] 我已经阅读了[相关文档](https://nonebot.dev/docs/next/best-practice/alconna/) 并仍然认为这是一个Bug

# Bug

## 问题
无法加载该插件

## 如何复现

安装nonebot_plugin_memes后nb run
## 预期行为

正常加载

## 使用环境:
- Python 版本:3.8 
- Nonebot2 版本:2.2.1
- Alconna 版本: 0.42.4

## 日志/截图

06-13 23:21:44 [SUCCESS] nonebot | Succeeded to load plugin "uniseg" from "nonebot_plugin_alconna.uniseg"
06-13 23:21:44 [ERROR] nonebot | Failed to import "nonebot_plugin_alconna"
Traceback (most recent call last):
  File "bot.py", line 29, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/home/ubuntu/tokiko/.venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/ubuntu/tokiko/.venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/ubuntu/tokiko/.venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/home/ubuntu/tokiko/.venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "/home/ubuntu/tokiko/.venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/ubuntu/tokiko/.venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/tokiko/.venv/lib/python3.8/site-packages/nonebot_plugin_memes/__init__.py", line 30, in <module>
    require("nonebot_plugin_alconna")
  File "/home/ubuntu/tokiko/.venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 179, in require
    plugin = load_plugin(name)
  File "/home/ubuntu/tokiko/.venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugin
    return manager.load_plugin(module_path)
> File "/home/ubuntu/tokiko/.venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/ubuntu/tokiko/.venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/tokiko/.venv/lib/python3.8/site-packages/nonebot_plugin_alconna/__init__.py", line 45, in <module>
    from .typings import AtID as AtID
  File "/home/ubuntu/tokiko/.venv/lib/python3.8/site-packages/nonebot_plugin_alconna/typings.py", line 23, in <module>
    class _Text(BasePattern[Text, str]):
  File "/usr/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.8/typing.py", line 897, in __class_getitem__
    _check_generic(cls, params)
  File "/home/ubuntu/tokiko/.venv/lib/python3.8/site-packages/typing_extensions.py", line 164, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} parameters for {cls};"
TypeError: Too few parameters for <class 'nepattern.core.BasePattern'>; actual 2, expected 3

**Comment by RF-Tar-Railt** [comment]
你升级啊
alc插件现在版本是0.46.5了

**Comment by cute-cirno** [comment]
0.46.5 Requires-Python >=3.9
也就是基本告别3.8了吗

**Comment by RF-Tar-Railt** [comment]
你bot有什么插件是锁死在3.8的吗

**Comment by RF-Tar-Railt** [comment]
如果你实在动不了你本地的python版本我可以发一个兼容3.8的版本（0.46.5-patch1）

**Comment by cute-cirno** [comment]
用miniconda更新了python版本，现在可以了，谢谢。
